name: Node Setup
description: Node.js setup for CI, including cache configuration
inputs:
  cache:
    description: cache of setup-node action, close on self-hosted runners
    required: false
    default: pnpm
  registry:
    description: registry to use for installing Node.js
    required: false
    default: https://registry.npmjs.org
  npmtoken:
    description: token for private registry
    required: false
    default: xxxx-xxxxx-xxxx-xxxx

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: ${{ inputs.cache }}
        registry-url: ${{ inputs.registry }}

    - name: Setup .npmrc
      run: |
        echo -e "\n//verdaccio.univer.work/:_authToken=${{ inputs.npmtoken }}" >> ${{ env.NPM_CONFIG_USERCONFIG }}
        cat ${{ env.NPM_CONFIG_USERCONFIG }}
      shell: bash

    - name: show npm registry
      run: npm config get registry
      shell: bash

    - name: Install dependencies
      run: pnpm install
      shell: bash
