name: 📦 Build

on:
  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          registry-url: ${{ secrets.VERDACCIO_URL }}
          node-auth-token: ${{ secrets.VERDACCIO_TOKEN }}

      - name: 🧪 Lint
        run: pnpm lint

      - name: 📦 Build
        run: pnpm run build

  set-pr-info:
    name: set PR info
    runs-on: ubuntu-latest
    steps:
      - name: Save PR info
        run: |
          echo ${{ github.event.pull_request.number }} > ./pr-id.txt
          echo ${{ github.head_ref }} >> ./pr-ref.txt
          echo ${{ github.event.pull_request.head.repo.full_name || github.repository }} >> ./pr-repo.txt

      - name: Upload PR number
        uses: actions/upload-artifact@v3
        with:
          name: pr-id
          path: ./pr-id.txt

      - name: Upload PR ref
        uses: actions/upload-artifact@v3
        with:
          name: pr-ref
          path: ./pr-ref.txt

      - name: Upload PR repo
        uses: actions/upload-artifact@v3
        with:
          name: pr-repo
          path: ./pr-repo.txt
