name: 🧪 CI Test

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ci-test-${{ github.sha }}
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          npmtoken: ${{ secrets.VERDACCIO_TOKEN }}

      - name: tsc type lint
        run: pnpm lint
